### ISSUE TITLE
unpkg.com vue-mapbox-map.umd.js link changed

### ISSUE THREAD

**Issue by gyansantokhi** [cityseer/vue-mapbox-feature#1]
The link to vue-mapbox-map.umd.js on unpkg.com has changed and now the [live demo](https://cityseer.github.io/vue-mapbox-feature/) stopped working. 

Old link: [
https://unpkg.com/vue-mapbox-map@latest/dist/vue-mapbox-map.umd.js](https://unpkg.com/vue-mapbox-map@latest/dist/vue-mapbox-map.umd.js)

New link: [https://unpkg.com/vue-mapbox-map@latest/dist/VueMapboxMap.umd.js](https://unpkg.com/vue-mapbox-map@latest/dist/VueMapboxMap.umd.js)

**Comment by songololo** [comment]
Thanks.

A few changes underway to `vuepress` docs and some bundling refinements.

New URLS per [updated docs](https://cityseer.github.io/vue-mapbox-feature/#setup-for-web-usage).
