### ISSUE TITLE
How to show points' labels?

### ISSUE THREAD

**Issue by JiahangOK** [cityseer/vue-mapbox-feature#8]
This is an amazing component. Now, I can show the Points, Polygon, and Lines on my mapbox. But besides that, I also want to show the points' labels on the map, or people cannot know what place it is. Can I do this using this component?

**Comment by songololo** [comment]
@JiahangOK glad you like the component.

At the moment the component is not designed for labels but I can have a think about whether it is something that makes sense to incorporate.

If you have ideas on how this functionality might work from a user's perspective, or how it might be implemented in a way that is fairly elegant and simple (and that doesn't bring too much complexity to the package) let me know.

**Comment by songololo** [comment]
@JiahangOK one other thing to keep in mind / question to ask:

Are your labels reactive? If they are relatively static then it may be better to simply load them directly into the map using conventional paradigms. My inclination is to use the mapbox GL JS instance directly wherever possible and to only wrap with reactive Vue modules where necessary (trying to avoid unnecessarily complex abstractions or duplication of functionality provided by the core library).
